### ISSUE TITLE
AdUnit image in the campaign preview disappears

### ISSUE THREAD

**Issue by TRtomasz** [heyAuraDev/adex-platform#355] opened 2020-02-24 22:08 UTC
**Describe the bug**
When we go to the campaign preview, we can see adunit image at the begining after few moments image is no longer visibile.

**To Reproduce**
1. Go through creating ~new adunit~ new campaign
2. On preview step wait around 20 seconds
3. Adunit image is no longer visible

**Expected behavior**
AdUnit image should be visible all the time 

**Screenshots**
![image](https://user-images.githubusercontent.com/40594253/75193352-60240a00-5756-11ea-8c62-62c9de89d9af.png)
![image](https://user-images.githubusercontent.com/40594253/75193370-674b1800-5756-11ea-8ef9-5079b6ca1307.png)

**Desktop (please complete the following information):**
Latest Firefox/ Windows 10

**Additional context**

**Comment by Ivshti** [comment] 2020-02-24 22:36
I don't think this is blocked by the relayer, looks like a pure platform bug

**Comment by rori4** [comment] 2020-02-25 12:55
I can't reproduce this on my end. This might be related to the IPFS server but everything seems fine when I do it on my end. Also have tested on chrome and firefox.

P.S.: In the description you said that this is and adUnit creation but the screenshots shows a campaign creation. I have corrected it.

**Comment by rori4** [comment] 2020-02-28 15:27
@TRtomasz Can you reproduce this again on your end?

**Comment by unbelievable-jeff** [comment] 2020-03-04 00:19
i noticed this too, my campaign had around 7 ad units, he last 3 or so would occasionally display the placeholder image. F5 corrected the glitch, clicking off the campaign and back into it recreated same error intermittently

**Comment by ivopaunov** [comment] 2020-03-11 09:23
looks fixed with https://github.com/AdExNetwork/adex-platform/pull/396

**Closed as completed by ivopaunov** 2020-03-11 09:23 UTC
Labels: bug
