### ISSUE TITLE
Unable to add more websites to an audience with manually selected sites

### ISSUE THREAD

**Issue by NadiaIv** [heyAuraDev/adex-platform#623] opened 2021-12-06 14:57 UTC
**Describe the bug**
We have recently started creating audiences with 'approved' publishers for own catch-all campaigns to stop new scummy publishers from syphoning our budgets. But once you've added some sites and saved (like over 100 sites) it doesn't let you add any more sites, just gives you the white screen of death (screenshot below - with dev console for your reference) once you click on Save

**To Reproduce**
1. Go to [platform](https://platform.adex.network/)
2. Log in with official adex account (official.adex.eth 0x033Ed90e0FeC3F3ea1C9b005C724D704501e0196)
3. Go to audiences, select one of the Approved Publisher ones and try and add any website -> click Save 

**Expected behavior**
It should update the audience

**Screenshots**
<img width="1428" alt="Screenshot 2021-12-06 at 15 48 13" src="https://user-images.githubusercontent.com/48917288/144868362-5578803b-eac5-4d49-b12a-c609f30c881d.png">

P.S. Assigning Sasho too so he can keep track of progress in my absence

**Comment by Vesi5** [comment] 2022-07-01 12:04
Adding the latest discussion with Paunov here as a reminder for when this bug will be fixed:

The issue at the moment is that if you attempt to edit an already existing audience and you add/remove publishers, then click Save, you will not be able to launch a campaign with the edited audience as it shows this error: 
![Screenshot 2022-06-28 at 12 01 55](https://user-images.githubusercontent.com/64790881/176889334-040fb556-8fec-4c46-a2c5-3fcfb3daa28a.png)

Paunov found out that there are "empty" publishers, or in other words publishers, who are not part of the network anymore. If those are not removed it will cause problems with the audience and campaigns created with it. I cannot add a screenshot of such publishers, since he fixed it for now. How to reproduce the issue:

1. Log in the [platform]([platform](https://platform.adex.network/))
2. Go to Audience
3. Open any existing audience, which has publishers selected in it 
4. Click on Edit Audience
5. Go to publishers
6. Click on +more button to expand the list 
7. if there are any empty bubbles, in which a domain should be listed and those are not removed before saving, a campaign with this audience cannot be launched.

@Alpina-BG

**Comment by Alpina-BG** [comment] 2022-12-05 15:41
At this point, this issue can be closed.
No longer need a fix.

**Closed as completed by Alpina-BG** 2022-12-05 15:41 UTC
Labels: bug
